#!/usr/bin/env -S uv tool run dotlocalslashbin --input

[tofu]
url = "https://github.com/opentofu/opentofu/releases/download/v1.10.3/tofu_1.10.3_linux_amd64.zip"
modifier = "_SHA256SUMS"
expected = "acf330602ec6ae29ba68dd5d8eb1f645811ae9809231ecdccd4774b21d5c79bc" # bin/update.py tofu
ignore = ["LICENSE", "README.md", "CHANGELOG.md"]
version = "version"

# test.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
